name: Build and deploy Python app to VPS

env:
  PYTHON_VERSION: '3.11.9'              # set this to the Python version to use

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy 
        id: deploy-to-webapp
        run: |
          cd /media/rasp/D1/imou
          ./fetch_source_code
        
